version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
            
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mv ROOT-1.0-SNAPSHOT.war ROOT.war
           
  post_build:
    commands:
      - echo Build completed on `date`
     
artifacts:
  files:
    - '**/ROOT.war'
  discard-paths: yes
